### PR TITLE
Bug fixes and updating things to newer versions

### PR DESCRIPTION
**Pull request by hankmander**
I really enjoyed this boilerplate for a recent project. I made some fixes that I might as well push upstream. Tell me if you prefer them split up in smaller pull requests as this one has 10 commits with different fixes. I'm also happy to answer questions about what things does.

Thanks for the good work!

### CODE REVIEW

**Comment by 1aurabrown** [comment]
Thank you! This was thrown onto github without full testing, and was a hybrid of a few different setups I'd used in the past. When I start projects with this starter, there are always things that are a bit broken and need fixing but I never took the time to merge those changes back into this repo. Please feel free to improve on this further!

**Comment by hankmander** [comment]
Happy that you liked the changes! We just published the site here https://www.airinum.com and got almost 3x the site speed. Sweet! We will probably use this boilerplate for more projects in the future so more changes might happen.

What is your stance on more opinionated stuff like typescript? We used ts for this project but I decided not to include it in the PR.

**Comment by 1aurabrown** [comment]
Hey @hankmander I don't have much experience with typescript to be honest. I actually just made a few changes myself which I will need to push up to a branch, mainly updating dependencies.

I have also started a branch which migrates this to Online Store 2.0 but I then found the new Online Store workflow so annoying that I gave up. Do you have any experience with that?

**Comment by 1aurabrown** [comment]
That being said, moving toward typescript could be a good thing for me to learn!

**Comment by hankmander** [comment]
Maybe typescript is a bit much to add to this, those that want do can pretty easily add it. We did for the site I mentioned.

Regarding Online Store 2.0, yes we ended up using it for the same site. Not very well documented by Shopify how to migrate, but once you have it's hard going back to a theme where you can't add and move sections everywhere you want. I could look into migrating this theme when I get some time if you want.

**Pull request merged**
